In [5]:
l1=[1,10.0,"Hello",1,234,"Hii",[10,100,111],("chiru","shree")]
print(l1)

[1, 10.0, 'Hello', 1, 234, 'Hii', [10, 100, 111], ('chiru', 'shree')]


In [8]:
l1=[10,20,30,40]
if 50 in l1:
    print("Exists")
else:
    print("Not")

Not


In [12]:
l1=[10,60,50,40,100]
print("Length of the list is:",len(l1))

Length of the list is: 5


In [14]:
l1=[]
for i in range(1,6):
    l1.append(i ** 2)
print(l1)

[1, 4, 9, 16, 25]


In [20]:
l1=[100,200,10,500,37]
l1.sort(reverse=True)
print(l1)

[500, 200, 100, 37, 10]


In [27]:
l1=[10,20,30,40]
l2=[50,20,60,10]
def cmp(l1,l2):
    if(set(l1)==set(l2)):
        print("Lists are equal")
    else:
        print("Lists are not equal")
    if(l1.sort()==l2.sort()):
        print("Sorted lists are equal")
    else:
        print("Sorted lists are not equal")
cmp(l1,l2)
    

Lists are not equal
Sorted lists are equal


In [29]:
l1=[100,200,56,78,23]
l1.remove(200)
print(l1)
l1.pop(3)
print(l1)
l1.clear()
print(l1)

[100, 56, 78, 23]
[100, 56, 78]
[]


In [30]:
import numpy as np
a=[10,20,30,40]
print("Integer array:")
print(a)
x=np.asfarray(a)
print("Array converted to float type:")
print(x)

Integer array
[10, 20, 30, 40]
Array converted to float type:
[10. 20. 30. 40.]


In [31]:
import numpy as np
l1=[10,20,60,100]
a1=np.array(l1)
t1=(100,200,300)
a2=np.array(t1)
print(l1)
print(t1)
print("After converting list into array")
print(a1)
print("After converting tuple into array")
print(a2)


[10, 20, 60, 100]
(100, 200, 300)
After converting list into array
[ 10  20  60 100]
After converting tuple into array
[100 200 300]


In [32]:
import numpy as np
l1=[10,20,60,100]
t1=(100,200,300)
a1=np.asarray(l1)
a2=np.asarray(t1)
print("After converting list into array")
print(a1)
print("After converting tuple into array")
print(a2)

After converting list into array
[ 10  20  60 100]
After converting tuple into array
[100 200 300]


In [33]:
import numpy as np
x=np.arange(2,6).reshape(4)
print(x)

[2 3 4 5]


In [34]:
import numpy as np
x=np.arange(2,10).reshape(2,4)
print(x)

[[2 3 4 5]
 [6 7 8 9]]


In [36]:
import numpy as np
x=np.arange(24).reshape(4,3,2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [1]:
a=int(input("Enter the first number:"))
b=int(input("Enter the second number:"))
if(a>b):
    min1=a
else:
    min1=b
while(1):
    if(min1%a==0 and min1%b==0):
        print("LCM is:",min1)
        break
    min1=min1+1

Enter the first number:12
Enter the second number:15
LCM is: 60
